config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pixars do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  root'pixars#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :pixar
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :pixar
  belongs_to :user
  validates_uniqueness_of :pixar_id, scope: :user_id
end

app/models/pixar.rb
class Pixar < ApplicationRecord
    belongs_to :user 
    mount_uploader :image, ImageUploader
    mount_uploader :video, VideoUploader
    has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :pixars, dependent: :destroy
         has_many :comments, dependent: :destroy
         has_many :likes, dependent: :destroy
         has_many :liked_pixars, through: :likes, source: :pixar
         def already_liked?(pixar)
          self.likes.exists?(pixar_id: pixar.id)
        end
        end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
        pixar = Pixar.find(params[:pixar_id])
        comment = pixar.comments.build(comment_params) 
        comment.user_id = current_user.id
        if comment.save
          flash[:success] = "コメントしました"
          redirect_back(fallback_location: root_path) 
        else
          flash[:success] = "コメントできませんでした"
          redirect_back(fallback_location: root_path)
        end
      end
      
      private

      def comment_params
        params.require(:comment).permit(:content)
      end
  end  

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(pixar_id: params[:pixar_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(pixar_id: params[:pixar_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/pixars_controller.rb
class PixarsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def index
        @pixars = Pixar.all
        @pixars = @pixars.page(params[:page]).per(3)
        @rank_pixars = Pixar.all.sort {|a,b| b.liked_users.count <=> a.liked_users.count}.first(3)
    end
    def new
        @pixar = Pixar.new
      end
    
      def create
        pixar= Pixar.new(pixar_params)

        pixar.user_id = current_user.id  

        if pixar.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @pixar = Pixar.find(params[:id])
        @comments = @pixar.comments
        @comment = Comment.new
      end

        

      def edit
        @pixar = Pixar.find(params[:id])
      end

      def update
        pixar = Pixar.find(params[:id])
        if pixar.update(pixar_params)
          redirect_to :action => "show", :id => pixar.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        pixar= Pixar.find(params[:id])
        pixar.destroy
        redirect_to action: :index
      end

      private
      def pixar_params
        params.require(:pixar).permit(:name, :main, :mouse, :video, :image)
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pixars_helper.rb
module PixarsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mystorygram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    
    <link href="https://fonts.googleapis.com/css2?family=Zen+Kurenaido&display=swap" rel="stylesheet">
    
    
    
    
    
    </head>
 
  <body>
  <header>
   <h1>My Golden Life</h1>
   <div class="header-list">
    <ul>
     <% if user_signed_in? %>
      <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
     <% else %>
      <li><%= link_to "新規登録", new_user_registration_path %></li>
      <li><%= link_to "ログイン", new_user_session_path %></li>
     <% end %>
    </ul>
   </div>
  </header>
  <main>
   <%= yield %>
  </main>
  <footer>
      <p>Copyright © GeekSalon All Rights Reserved.</p>
    </footer>
 </body>
</html>

app/views/pixars/edit.html.erb
<%= stylesheet_link_tag 'pixars', :media => "all" %>
<%= link_to "一覧ページへ",  pixars_path %>
<%= form_for @pixar do |f| %>
  
    <div class="vegetable">
    <%= image_tag "vegetarians" %>
    </div>
    
    <div class="field">
      <%= f.label :タイトル %>
      <%= f.text_field :name, :size => 30 %>
    </div>
     
     <div class="field">
     <%= f.label :画像 %>
     <%= f.file_field :image, :size => 30 %>
   </div>
    
        
    <div class="field">
      <%= f.label :動画 %>
      <%= f.file_field :video, :accept => 'video/*' %>
    </div>


    <div class="field">
      <%= f.label :本文 %>
      <%= f.text_area :main, :size => "30x2" %>
    </div>

    <div class="field">
      <%= f.label :備考欄  %>
      <%= f.text_area :mouse, :size => "30x2" %>
    </div> 

   <%= f.submit "編集する" %>
<% end %>
<%= link_to "Pixar一覧に戻る", pixars_path %>
<%= link_to "編集する", edit_pixar_path(@pixar.id) %>

app/views/pixars/index.html.erb
<div class="ribbon2">
  <h1>Welcome to My golden life!</h1>
</div>
<div class="photo">
<h1></h1>
</div>
<%= stylesheet_link_tag 'index', :media => "all" %>
<h3>一覧ページ</h3>
<% if user_signed_in? %>
  <% if current_user == @user || current_user.admin? %>
    <%= link_to "新規投稿へ", new_pixar_path %>
  <% end %>
<% end %>
<%= page_entries_info @pixars %>
<%= paginate @pixars %>
<div class="pixars-container">
  <% @pixars.each do |t| %>
    <div class="pixar">
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= t.user.email %> 
      <%= t.name %>
      <%= t.main %>
      <%= t.mouse %>
      <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
            <%= link_to pixar_like_path(id: t.id, pixar_id: t.id), method: :delete do %>
                <p>いいねを取り消す</p><%= t.likes.count %>
            <% end %>
        <% else %>
            <%= link_to pixar_likes_path(id: t.id, pixar_id: t.id), method: :post do %>
                <p>いいね</p><%= t.likes.count %>
            <% end %>
        <% end %>
      <% else %>
        <p>いいねの数 = </p><%= t.likes.count %>
      <% end %>

      <%= link_to "詳細へ", pixar_path(t.id) %>

      <% if user_signed_in? && current_user.id == t.user_id %>
        <%= link_to "編集する", edit_pixar_path(t.id) %>
        <%= button_to "削除する", pixar_path(t.id), method: :delete %> 
      <% end %> 
    </div>
  <% end %> 
<h4>いいね！ランキング</h4>  
  <% @rank_pixars.each do |t| %>
    <div class="pixar1">
        <%= image_tag t.image_url, size: "250x200" if t.image? %>
        <%= t.user.email %> 
        <%= t.name %>
        <%= t.main %>
        <%= t.mouse %>
        <%= t.video %>
        <p>いいねの数 = </p><%= t.likes.count %>
    </div>
    <p class="time"><%= t.created_at %></p>
    </div>
    <% end %>
</div>

app/views/pixars/new.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
<%= stylesheet_link_tag 'new', :media => "all" %>
</head>

<body>

  <h3>新規投稿ページ</h3>

  <div class="new">
   <%= image_tag "z8Iq8iJ1PZUybLx42F1BXmCTBaz" %>
   
  </div>


  <%= form_for @pixar do |f| %>

  
    <div class="field">
      <%= f.label :タイトル %>
      <%= f.text_field :name, :size => 30 %>
      <%= f.label :投稿内容 %>
        <br>
        <%= f.text_field :main, :size => 140%>
        <br>
    </div>
     
    <div class="field">
      <%= f.label :画像 %>
      <%= f.file_field :image %>
    </div>
 
    
    <div class="field">
      <%= f.label :動画 %>
      <%= f.file_field :video, :accept => 'video/*' %>
    </div>


    <div class="field">
      <%= f.label :本文 %>
      <%= f.text_area :main, :size => "30x2" %>
    </div>

    <div class="field">
     <%= f.label :備考欄 %>
     <%= f.text_area :mouse, :size => "30x2" %>
    </div>

    <%= f.submit "投稿する" %>
    <% end %>



  <%= link_to "一覧に戻る", pixars_path %>
  
</body>

</html>

app/views/pixars/show.html.erb
<%= stylesheet_link_tag 'pixars', :media => "all" %>
<h1>My Golden Life</h1>
<h3>Pixar詳細</h3>

<%= link_to "一覧ページへ",  pixars_path %>

<div class="sea">
<%= image_tag "OIP" %>
</div>
<div class="pixar">
  <p><%= @pixar.main %></p>
  <p><%= @pixar.name %></p>
  <p><%= @pixar.mouse %></p>
  <p><%= image_tag @pixar.image_url, size: "250×200" if @pixar.image? %></p>
  <%= link_to @pixar.video_url.to_s do %>
    <%= video_tag(@pixar.video.to_s, controls:true, controlslist: 'nodownload', size: "700x300") if @pixar.video?%>
   <% end %>
  <p><%= @pixar.created_at %></p>
  <p><%= @pixar.updated_at %></p>
</div>
<% if user_signed_in? %>
      <% if current_user.already_liked?(@pixar) %>
        <%= link_to pixar_like_path(@pixar), method: :delete do %>
          <i class="far fa-heart"></i><%= @pixar.likes.count %>  
    
        <% end %>
      <% else %>
        <%= link_to pixar_likes_path(@pixar), method: :post do %>
          <i class="far fa-heart"></i><%= @pixar.likes.count %>  
        <% end %>
      <% end %>
    <% else %>
    <i class="far fa-heart"></i><%= @pixar.likes.count %>  
    <% end %>
    <h2>いいねしたユーザー</h2>
<% @pixar.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@pixar, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>
<%= link_to "Pixar一覧に戻る", pixars_path %>
<%= link_to "編集する", edit_pixar_path(@pixar.id) %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>